"""Added verification_document_path to Vet model

Revision ID: 75013ff3e007
Revises: 4189d98a23c6
Create Date: 2025-02-18 11:59:39.827291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75013ff3e007'
down_revision = '4189d98a23c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_document_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.drop_column('verification_document_path')

    # ### end Alembic commands ###
