"""sets the farm_location field to nullable

Revision ID: ac99c05b1fd7
Revises: 75013ff3e007
Create Date: 2025-02-18 15:41:11.742853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac99c05b1fd7'
down_revision = '75013ff3e007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.alter_column('farm_location',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.alter_column('farm_location',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
